name: Node.js Package
# https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml
on:
  #  [push]
  release:
    types: [ created ]
# https://github.com/actions/starter-workflows/issues/158
# redis
# redis
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
    services:
      redis:
        image: redis:4.0.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --dev
      - run: npm run build
      - run: npm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}